# Generated by Django 4.0.2 on 2022-04-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_name_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Email')),
                ('task', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2, verbose_name='Message')),
                ('task', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Phone')),
                ('task', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='name',
            name='task',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
