# Generated by Django 4.0.2 on 2022-04-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_email_message_phone_alter_name_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='task',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='task',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='task',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='task',
            new_name='Phone',
        ),
    ]
