# Generated by Django 4.0.2 on 2022-04-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_phone_phone_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='title',
        ),
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.RemoveField(
            model_name='name',
            name='title',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='title',
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=20, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
    ]
