# Generated by Django 4.0.2 on 2022-05-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_comments_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Comments'),
        ),
    ]
